### ISSUE TITLE
NPE when creating task and "Hide completed tasks" is checked

### ISSUE THREAD

**Issue by pamtbaau** [NLSurfMan/tasks#21]
When a new task is created while the option "Hide completed tasks" is checked the following error will be raised:
"NullPointerException: Null child not allowed: Null child not allowed"

Task will be created but remains invisible until "Hide completed tasks" is unchecked

**Comment by NLSurfMan** [comment]
This bug no longes comes up in IDEA 2016.1.

**Comment by pamtbaau** [comment]
Just wait long enough and a fix will happen by itself :-)

**Comment by NLSurfMan** [comment]
Yeah, sorry about that. I just can't find the time to update this plugin. I am working on bringing it up to standards now. I hope to commit something useful soon.

**Comment by pamtbaau** [comment]
No need to be sorry, it is already fine the way it is.
