### ISSUE TITLE
Not working in PyCharm

### ISSUE THREAD

**Issue by pamtbaau** [NLSurfMan/tasks#26]
Any reason why this plugin doesn't work in PyCharm? After installing the plugin remains grayed out.

**Comment by NLSurfMan** [comment]
I didn't specifically **disable** the plugin for PyCharm. I haven't tested it. Will do and fix (if I can). Thanks for the report.

**Comment by NLSurfMan** [comment]
Happy to report that this plugin should now work on all IntelliJ platforms 2016 and higher.
