### ISSUE TITLE
AWT events are not allowed inside write action

### ISSUE THREAD

**Issue by SebastianKaczanowski** [NLSurfMan/tasks#27]
When adding from //fixme in code (using alt enter) and attaching it to some subtask as its subtask below error appears although task is added properly. 

AWT events are not allowed inside write action: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.intellij.openapi.util.ActionCallback$$Lambda$290/1184610037@859a8ec,notifier=null,catchExceptions=false,when=1490279199115] on sun.awt.windows.WToolkit@4c52561d

**Comment by NLSurfMan** [comment]
Thanks for reporting this. I fixed this and will be included in the next update of the plugin.

**Comment by SebastianKaczanowski** [comment]
Thank you for a great tool and great reaction :) I've tested it. it is working now without any issue :)
