### ISSUE TITLE
different task lists for different projects

### ISSUE THREAD

**Issue by alyamovsky** [NLSurfMan/tasks#30]
Hi there! Do you plan to add the feature to set different task lists for different projects in PHPStorm?

**Comment by NLSurfMan** [comment]
There is a feature I planned (https://github.com/NLSurfMan/tasks/issues/2) that would support this. It's hard to spend time on this project, but I'll start working on this asap.

**Comment by pavelhlushchanka** [comment]
Yeah, that would be an extremely useful feature.
