### ISSUE TITLE
“Start work” button not work

### ISSUE THREAD

**Issue by liuyibo123** [NLSurfMan/tasks#38]
The "Start work" button not work 
![image](https://user-images.githubusercontent.com/18073646/69936495-f27b8f80-1512-11ea-8660-c1d0044badde.png)

**Comment by NLSurfMan** [comment]
You need to enable the "actual time feature"

![image](https://user-images.githubusercontent.com/5594197/70230674-1defbb80-1759-11ea-9b58-d47f655cdbcf.png)
